#' Interpret Epidemiological Data or Visualisations using LLMs
#'
#' This function interprets a given data frame or ggplot visualization
#' by sending it to a language model API  via the elmer package.
#'
#' @param input An input object which can either be a data frame or a ggplot object.
#' @param word_limit The desired word length for the response. Defaults to 100.
#' @param prompt_extension Optional additional instructions to extend the standard prompt.
#' @return A narrative or interpretation of the input object as generated by the LLM.
#' @import ggplot2
#' @importFrom jsonlite toJSON
#' @import elmer
#' @export
llm_interpret <- function(input,
                          word_limit = 100,
                          prompt_extension = NULL) {
  # Retrieve API key and model from environment variables
  api_key <- Sys.getenv("OPENAI_API_KEY")
  model <- Sys.getenv("LLM_MODEL")

  # Initialize the chat client with OpenAI and the specified model
  chat <- chat_openai(
    model = model,
    api_key = api_key,
    system_prompt = "You are a concise assistant focusing on epidemiologically relevant observations.",
    echo = FALSE
  )

  # Define the standard prompt
  standard_prompt <- paste(
    "Please provide an interpretation focusing on the most epidemiologically relevant observations in",
    word_limit,
    "words or fewer."
  )

  # Append the prompt extension if provided
  if (!is.null(prompt_extension)) {
    standard_prompt <- paste(standard_prompt, prompt_extension)
  }

  # Case: Input is a data frame
  if (is.data.frame(input)) {
    # Convert data frame to JSON
    json_data <- jsonlite::toJSON(input, pretty = TRUE, auto_unbox = TRUE)

    # Send JSON data to the API
    response <- chat$chat(standard_prompt, json_data)

    return(response)
  }

  # Case: Input is a ggplot object
  else if (inherits(input, "ggplot")) {
    # Save the ggplot object as a temporary image
    temp_file <- tempfile(fileext = ".png")
    ggplot2::ggsave(
      temp_file,
      plot = input,
      width = 6,
      height = 4,
      dpi = 300
    )

    # Send image file to the API
    response <- chat$chat(content_image_file(temp_file), standard_prompt)

    # Remove temporary file after use
    unlink(temp_file)

    return(response)
  }

  # Handle unexpected input types
  else {
    stop("Input must be a data frame or a ggplot object.")
  }
}
